FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY app.js     /usr/share/nginx/html/app.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY admin.html /usr/share/nginx/html/admin.html
COPY admin.js   /usr/share/nginx/html/admin.js
COPY admin.css  /usr/share/nginx/html/admin.css

EXPOSE 80
